### ユーザー登録のテスト
POST http://localhost:8787/auth/signup
Content-Type: application/json

{
  "email": "test1@example.com",
  "password": "password123"
}

### ログインのテスト
POST http://localhost:8787/auth/login
Content-Type: application/json

{
  "email": "test@example.com",
  "password": "password123"
}

### 1. ログインしてトークンをゲットする
POST http://localhost:8787/auth/login
Content-Type: application/json

{
    "email": "test1@example.com",
    "password": "password123"
}

### 2. 自分の情報を取得する (/me)
# 上のログインで返ってきた "token" の中身をコピーして、Bearer の後ろに貼り付ける
GET http://localhost:8787/me
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJmOTU4N2ZlNy1hZmMwLTRmYTYtYmM5Mi0wM2UzZGFjYmU0OWYiLCJlbWFpbCI6InRlc3QxQGV4YW1wbGUuY29tIiwiZXhwIjoxNzY1NTUyMjgwfQ.xYE3QMXWlJ6OzV6hGyZfxUd2U-DtsF3qgEs16Is7xjk

### プロフィール更新
PATCH http://localhost:8787/me
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJmOTU4N2ZlNy1hZmMwLTRmYTYtYmM5Mi0wM2UzZGFjYmU0OWYiLCJlbWFpbCI6InRlc3QxQGV4YW1wbGUuY29tIiwiZXhwIjoxNzY1NTUyMjgwfQ.xYE3QMXWlJ6OzV6hGyZfxUd2U-DtsF3qgEs16Is7xjk
Content-Type: application/json

{
  "username": "hui",
  "description": "プロフィール更新できたよん!",
  "iconUrl": "ijkjkiuh.png"
}